services:
  - type: web
    name: arpit-portfolio
    env: static
    buildCommand: |
      export NODE_OPTIONS=--openssl-legacy-provider
      npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - build/**
    envVars:
      - key: NODE_VERSION
        value: 18.20.3
